# Generated by Django 3.2.2 on 2021-10-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211005_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('prod_name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(max_length=250)),
                ('tot_price', models.IntegerField(max_length=250)),
                ('seller', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
