# Generated by Django 3.2.2 on 2021-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=10)),
                ('sup_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
    ]
